name: Build and push deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: build
        run: docker build -t ${{ secrets.NAME }}/cw2_flask_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: login
        run: docker login -u ${{ secrets.NAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: push
        run: docker push ${{ secrets.NAME }}/cw2_flask_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
